### ISSUE TITLE
Crash on MC 1.18.1, also submitted to Super Circuit Maker and Dynamic Electricity

### ISSUE THREAD

**Issue by Delta4Phoenix** [TechnicalitiesMC/TKLib#1] opened 2022-01-12 12:31 UTC
Exception in thread "main" java.lang.module.ResolutionException: Modules tklib and supercircuitmaker export package com.technicalitiesmc.lib to module dynamicelectricity
	at java.base/java.lang.module.Resolver.resolveFail(Resolver.java:901)
	at java.base/java.lang.module.Resolver.failTwoSuppliers(Resolver.java:815)
	at java.base/java.lang.module.Resolver.checkExportSuppliers(Resolver.java:736)
	at java.base/java.lang.module.Resolver.finish(Resolver.java:380)
	at java.base/java.lang.module.Configuration.<init>(Configuration.java:140)
	at java.base/java.lang.module.Configuration.resolveAndBind(Configuration.java:494)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.ModuleLayerHandler.buildLayer(ModuleLayerHandler.java:70)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.TransformationServicesHandler.buildTransformingClassLoader(TransformationServicesHandler.java:61)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.run(Launcher.java:104)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.Launcher.main(Launcher.java:77)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26)
	at MC-BOOTSTRAP/cpw.mods.modlauncher@9.0.7/cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23)
	at cpw.mods.bootstraplauncher@0.1.17/cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:90)

**Comment by amadornes** [comment] 2022-01-12 14:35
The crash is slightly different from TechnicalitiesMC/SuperCircuitMaker#9, but that's due to Forge loading mods in a random order. It's the same crash and it's caused by SCM, so I'll close this and you can refer to the other issue going forward.

**Closed as completed by amadornes** 2022-01-12 14:35 UTC
Labels: bug, duplicate
